/// <reference path="../../src/types/weiwudi.d.ts" />
import { XYZ } from "ol/source";
declare const NowMap_base: ((abstract new (...args: any[]) => {
    insideCheckXy(xy: import("ol/coordinate").Coordinate): boolean;
    insideCheckSysCoord(histCoords: import("ol/coordinate").Coordinate): boolean;
    modulateXyInside(xy: any): any;
    modulateSysCoordInside(histCoords: any): any;
    merc2XyAsync(merc: import("ol/coordinate").Coordinate): Promise<import("ol/coordinate").Coordinate>;
    merc2XyAsync_ignoreBackground(merc: import("ol/coordinate").Coordinate): Promise<void | import("ol/coordinate").Coordinate>;
    xy2MercAsync(xy: import("ol/coordinate").Coordinate): Promise<import("ol/coordinate").Coordinate>;
    xy2SysCoord(xy: import("ol/coordinate").Coordinate): import("ol/coordinate").Coordinate;
    sysCoord2Xy(sysCoord: import("ol/coordinate").Coordinate): import("ol/coordinate").Coordinate;
    viewpoint2MercsAsync(viewpoint?: import("./mixin").ViewpointArray | undefined, size?: import("ol/size").Size | undefined): Promise<import("./mixin").CrossCoordinatesArray>;
    mercs2ViewpointAsync(mercs: import("./mixin").CrossCoordinatesArray): Promise<import("./mixin").ViewpointArray>;
    mercs2SysCoordsAsync_multiLayer(mercs: import("./mixin").CrossCoordinatesArray): Promise<(import("./mixin").CrossCoordinatesArray | undefined)[]>;
    defZoom(): number;
    weiwudi?: import("weiwudi").default | undefined;
    _map?: import("../map_ex").MaplatMap | undefined;
    homePosition?: import("ol/coordinate").Coordinate | undefined;
    mercZoom?: number | undefined;
    pois: any;
    officialTitle: string;
    title: string;
    mapID: string;
    label: string;
    initialWait?: Promise<any> | undefined;
    maxZoom?: number | undefined;
    minZoom?: number | undefined;
    envelope?: import("@turf/turf").Feature<import("@turf/turf").Polygon, import("@turf/turf").Properties> | undefined;
    centroid?: number[] | undefined;
    homeMarginPixels: number;
    thumbnail?: string | undefined;
    poiTemplate?: string | undefined;
    poiStyle?: string | undefined;
    iconTemplate?: string | undefined;
    startFrom?: string | undefined;
    controls?: any[] | undefined;
    northUp?: boolean | undefined;
    tapDuration?: number | undefined;
    mercatorXShift: number;
    mercatorYShift: number;
    icon?: string | undefined;
    selectedIcon?: string | undefined;
    initialize(options: any): void;
    isBasemap(): any;
    isWmts(): any;
    isMapbox(): any;
    getCacheEnable(): boolean;
    getTileCacheStatsAsync(): Promise<{
        size?: number | undefined;
        count?: number | undefined;
        total?: number | undefined;
        percent?: number | undefined;
    }>;
    getTileCacheSizeAsync(): Promise<number>;
    fetchAllTileCacheAsync(callback: any): Promise<void>;
    cancelTileCacheAsync(): Promise<void>;
    clearTileCacheAsync(): Promise<void>;
    getMap(): import("../map_ex").MaplatMap;
    setMap(map: import("../map_ex").MaplatMap): void;
    setViewpointRadian(cond: {
        x?: number | undefined;
        y?: number | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
        mercZoom?: number | undefined;
        zoom?: number | undefined;
        direction?: number | undefined;
        rotation?: number | undefined;
    }): void;
    setViewpoint(cond: {
        x?: number | undefined;
        y?: number | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
        mercZoom?: number | undefined;
        zoom?: number | undefined;
        direction?: number | undefined;
        rotation?: number | undefined;
    }): void;
    goHome(): void;
    resetRotation(): void;
    resetDirection(): void;
    resetCirculation(): void;
    setGPSMarkerAsync(position: any, ignoreMove?: boolean): Promise<unknown>;
    setGPSMarker(position: any, ignoreMove?: boolean): void;
    mercsFromGPSValue(lnglat: import("ol/coordinate").Coordinate, acc: number): number[][];
    rotateMatrix(xys: number[][], theta?: number | undefined): import("ol/coordinate").Coordinate[];
    resolvePois(pois?: any): Promise<void>;
    getPoi(id: string): undefined;
    addPoi(data: any, clusterId?: string | undefined): any;
    removePoi(id: string): void;
    clearPoi(clusterId?: string | undefined): void;
    listPoiLayers(hideOnly?: boolean, nonzero?: boolean): any[];
    getPoiLayer(id: string): any;
    addPoiLayer(id: string, data: any): void;
    removePoiLayer(id: string): void;
    merc2SysCoordAsync_ignoreBackground(merc: import("ol/coordinate").Coordinate): Promise<void | import("ol/coordinate").Coordinate>;
    merc2SysCoordAsync(merc: import("ol/coordinate").Coordinate): Promise<import("ol/coordinate").Coordinate>;
    sysCoord2MercAsync(sysCoord: import("ol/coordinate").Coordinate): Promise<import("ol/coordinate").Coordinate>;
    zoom2Radius(size: import("ol/size").Size, zoom?: number | undefined): number;
    viewpoint2SysCoords(viewpoint?: import("./mixin").ViewpointArray | undefined, size?: import("ol/size").Size | undefined): import("./mixin").CrossCoordinatesArray;
    mercViewpoint2Mercs(viewpoint?: import("./mixin").ViewpointArray | undefined, size?: import("ol/size").Size | undefined): import("./mixin").CrossCoordinatesArray;
    sysCoords2Viewpoint(sysCoords: import("./mixin").CrossCoordinatesArray): import("./mixin").ViewpointArray;
    mercs2MercViewpoint(mercs: import("./mixin").CrossCoordinatesArray): import("./mixin").ViewpointArray;
    sysCoords2Xys(sysCoords: import("./mixin").CrossCoordinatesArray): import("./mixin").CrossCoordinatesArray;
    xys2SysCoords(xys: import("./mixin").CrossCoordinatesArray): import("./mixin").CrossCoordinatesArray;
    mercs2XysAsync(mercs: import("./mixin").CrossCoordinatesArray): Promise<import("./mixin").CrossCoordinatesArray>;
    xys2MercsAsync(xys: import("./mixin").CrossCoordinatesArray): Promise<import("./mixin").CrossCoordinatesArray>;
}) & {
    isBasemap_: boolean;
    isWmts_: boolean;
    isMapbox_: boolean;
    isBasemap(): boolean;
    isWmts(): boolean;
    isMapbox(): boolean;
    createAsync(options: any): Promise<any>;
}) & typeof XYZ;
export declare class NowMap extends NowMap_base {
    constructor(options?: any);
}
export {};
